export type ShareImage = { path: string; type: 'image/png' | 'image/jpeg' | 'image/webp'; width: number; height: number; alt: string };

// Generated by scripts/build-share-image.mjs; keep dimensions in sync with that script.
export const defaultShareImage: ShareImage = {
  path: '/og-image.png',
  type: 'image/png',
  width: 1200,
  height: 630,
  alt: 'useclis: command-line tools for coding agents. Find a CLI by task, inspect its repository, and hand your agent the catalog.',
};
