// Generated from the checked-in catalog and repository snapshots.
window.USECLIS_DATA = {
  "tools": [
    {
      "slug": "github-cli",
      "name": "GitHub CLI",
      "repo": "cli/cli",
      "category": "Git & collaboration",
      "command": "gh",
      "useCase": "GitHub workflows",
      "description": "Inspect repositories, issues, and pull requests from the terminal.",
      "agentUse": "Use GitHub commands and structured output to work with repository metadata and review workflows.",
      "features": [
        "Repository inspection",
        "Pull requests and issues",
        "JSON output"
      ],
      "example": "gh repo view --json name,description,stargazerCount",
      "featured": true,
      "website": "https://github.com/cli/cli#readme",
      "docs": "https://cli.github.com/manual/",
      "stars": 46214,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:50:54.851Z"
    },
    {
      "slug": "agent-browser",
      "name": "agent-browser",
      "repo": "vercel-labs/agent-browser",
      "category": "Browser automation",
      "command": "agent-browser",
      "useCase": "Browser interaction",
      "description": "Control a browser through a CLI designed for AI agents.",
      "agentUse": "Give an agent browser actions and accessibility snapshots with element references.",
      "features": [
        "Browser navigation",
        "Accessibility snapshots",
        "Screenshots"
      ],
      "example": "agent-browser --help",
      "featured": true,
      "website": "https://github.com/vercel-labs/agent-browser#readme",
      "docs": "https://github.com/vercel-labs/agent-browser#readme",
      "stars": 42312,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:54.889Z"
    },
    {
      "slug": "ripgrep",
      "name": "ripgrep",
      "repo": "BurntSushi/ripgrep",
      "category": "Code search",
      "command": "rg",
      "useCase": "Search source code",
      "description": "Search files and source code quickly with regular expressions.",
      "agentUse": "Find relevant code and return line matches or JSON events to an agent.",
      "features": [
        "Recursive search",
        "Regular expressions",
        "JSON output"
      ],
      "example": "rg --json \"TODO\" src",
      "featured": true,
      "website": "https://github.com/BurntSushi/ripgrep#readme",
      "docs": "https://github.com/BurntSushi/ripgrep#readme",
      "stars": 68132,
      "license": "Unlicense",
      "checkedAt": "2026-09-09T23:50:54.753Z"
    },
    {
      "slug": "jq",
      "name": "jq",
      "repo": "jqlang/jq",
      "category": "Data & APIs",
      "command": "jq",
      "useCase": "Process JSON",
      "description": "Filter, transform, and extract values from JSON on the command line.",
      "agentUse": "Turn API responses into small structured results that an agent can consume.",
      "features": [
        "JSON filtering",
        "Data transformation",
        "Shell pipelines"
      ],
      "example": "jq '.name' package.json",
      "featured": true,
      "website": "https://github.com/jqlang/jq#readme",
      "docs": "https://jqlang.org/manual/",
      "stars": 35559,
      "license": null,
      "checkedAt": "2026-09-09T23:50:54.824Z"
    },
    {
      "slug": "codex",
      "name": "Codex CLI",
      "repo": "openai/codex",
      "category": "Agents & models",
      "command": "codex",
      "useCase": "Coding agent",
      "description": "Run a coding agent from the terminal against a local codebase.",
      "agentUse": "Use a terminal coding agent to inspect a project and carry out coding tasks.",
      "features": [
        "Terminal coding agent",
        "Codebase workflows",
        "Command-line interface"
      ],
      "example": "codex --help",
      "featured": false,
      "website": "https://github.com/openai/codex#readme",
      "docs": "https://github.com/openai/codex#readme",
      "stars": 122838,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:55.747Z"
    },
    {
      "slug": "gemini-cli",
      "name": "Gemini CLI",
      "repo": "google-gemini/gemini-cli",
      "category": "Agents & models",
      "command": "gemini",
      "useCase": "Coding agent",
      "description": "Work with Gemini in the terminal for coding and development tasks.",
      "agentUse": "Run model-assisted development workflows from a command-line entry point.",
      "features": [
        "Terminal agent",
        "Development workflows",
        "Command-line interface"
      ],
      "example": "gemini --help",
      "featured": false,
      "website": "https://github.com/google-gemini/gemini-cli#readme",
      "docs": "https://github.com/google-gemini/gemini-cli#readme",
      "stars": 106879,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:55.796Z"
    },
    {
      "slug": "aider",
      "name": "Aider",
      "repo": "Aider-AI/aider",
      "category": "Agents & models",
      "command": "aider",
      "useCase": "AI pair programming",
      "description": "Edit a local codebase with a terminal-based AI pair programmer.",
      "agentUse": "Pair model-driven changes with a Git-based development workflow.",
      "features": [
        "AI code editing",
        "Git integration",
        "Terminal workflow"
      ],
      "example": "aider --help",
      "featured": false,
      "website": "https://github.com/Aider-AI/aider#readme",
      "docs": "https://github.com/Aider-AI/aider#readme",
      "stars": 48858,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:55.647Z"
    },
    {
      "slug": "opencode",
      "name": "OpenCode",
      "repo": "anomalyco/opencode",
      "category": "Agents & models",
      "command": "opencode",
      "useCase": "Coding agent",
      "description": "Use a terminal coding agent with support for multiple model providers.",
      "agentUse": "Choose a coding-agent runtime for working on a repository from the terminal.",
      "features": [
        "Terminal coding agent",
        "Model providers",
        "Repository workflows"
      ],
      "example": "opencode --help",
      "featured": false,
      "website": "https://github.com/anomalyco/opencode#readme",
      "docs": "https://github.com/anomalyco/opencode#readme",
      "stars": 206164,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:50:55.618Z"
    },
    {
      "slug": "llm",
      "name": "LLM",
      "repo": "simonw/llm",
      "category": "Agents & models",
      "command": "llm",
      "useCase": "Model access",
      "description": "Call language models and manage prompts from the command line.",
      "agentUse": "Connect shell pipelines to model calls through a scriptable CLI.",
      "features": [
        "Model prompts",
        "CLI pipelines",
        "Model plugins"
      ],
      "example": "llm --help",
      "featured": false,
      "website": "https://github.com/simonw/llm#readme",
      "docs": "https://github.com/simonw/llm#readme",
      "stars": 12481,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:56.554Z"
    },
    {
      "slug": "playwright-cli",
      "name": "Playwright CLI",
      "repo": "microsoft/playwright-cli",
      "category": "Browser automation",
      "command": "playwright-cli",
      "useCase": "Browser testing",
      "description": "Run browser actions, inspect pages, and take screenshots from the terminal.",
      "agentUse": "Give coding agents a CLI for browser interactions and test-oriented page inspection.",
      "features": [
        "Browser actions",
        "Page inspection",
        "Screenshots"
      ],
      "example": "playwright-cli --help",
      "featured": false,
      "website": "https://github.com/microsoft/playwright-cli#readme",
      "docs": "https://github.com/microsoft/playwright-cli#readme",
      "stars": 13193,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:56.729Z"
    },
    {
      "slug": "browser-harness",
      "name": "Browser Harness",
      "repo": "browser-use/browser-harness",
      "category": "Browser automation",
      "command": "browser-harness",
      "useCase": "Browser agents",
      "description": "Give an existing agent browser access through a command-line harness.",
      "agentUse": "Connect an agent to browser workflows through the dedicated Browser Use CLI repository.",
      "features": [
        "Browser access",
        "Agent workflow helpers",
        "Command-line interface"
      ],
      "example": "browser-harness --help",
      "featured": false,
      "website": "https://github.com/browser-use/browser-harness#readme",
      "docs": "https://github.com/browser-use/browser-harness#readme",
      "stars": 17456,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:54:51.437Z"
    },
    {
      "slug": "git",
      "name": "Git",
      "repo": "git/git",
      "category": "Git & collaboration",
      "command": "git",
      "useCase": "Version control",
      "description": "Inspect changes, history, branches, and repository state from the terminal.",
      "agentUse": "Use stable Git commands to understand working-tree changes and repository history.",
      "features": [
        "Version control",
        "Diff inspection",
        "Repository history"
      ],
      "example": "git status --short",
      "featured": false,
      "website": "https://github.com/git/git#readme",
      "docs": "https://github.com/git/git#readme",
      "stars": 63090,
      "license": null,
      "checkedAt": "2026-09-09T23:50:56.619Z"
    },
    {
      "slug": "git-town",
      "name": "Git Town",
      "repo": "git-town/git-town",
      "category": "Git & collaboration",
      "command": "git town",
      "useCase": "Branch workflows",
      "description": "Manage development branches and contribution workflows through Git commands.",
      "agentUse": "Use a CLI for repeatable branch workflows, following the project’s documented commands.",
      "features": [
        "Branch workflows",
        "Git integration",
        "Contribution workflows"
      ],
      "example": "git town --help",
      "featured": false,
      "website": "https://github.com/git-town/git-town#readme",
      "docs": "https://github.com/git-town/git-town#readme",
      "stars": 3373,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:50:57.532Z"
    },
    {
      "slug": "wrangler",
      "name": "Wrangler",
      "repo": "cloudflare/workers-sdk",
      "category": "Cloud & deployment",
      "command": "wrangler",
      "useCase": "Cloudflare projects",
      "description": "Develop and manage Cloudflare Workers projects from the terminal.",
      "agentUse": "Give an agent a command-line interface for Cloudflare development and deployment tasks.",
      "features": [
        "Workers development",
        "Local development",
        "Deployment commands"
      ],
      "example": "npx wrangler --help",
      "featured": false,
      "website": "https://github.com/cloudflare/workers-sdk#readme",
      "docs": "https://developers.cloudflare.com/workers/wrangler/",
      "stars": 4522,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:57.550Z"
    },
    {
      "slug": "vercel-cli",
      "name": "Vercel CLI",
      "repo": "vercel/vercel",
      "category": "Cloud & deployment",
      "command": "vercel",
      "useCase": "Vercel projects",
      "description": "Manage Vercel projects and deployment workflows from the command line.",
      "agentUse": "Use the CLI to inspect a Vercel project and run documented platform workflows.",
      "features": [
        "Project commands",
        "Deployment workflows",
        "Local development"
      ],
      "example": "vercel --help",
      "featured": false,
      "website": "https://github.com/vercel/vercel#readme",
      "docs": "https://github.com/vercel/vercel#readme",
      "stars": 16225,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:57.503Z"
    },
    {
      "slug": "supabase-cli",
      "name": "Supabase CLI",
      "repo": "supabase/cli",
      "category": "Cloud & deployment",
      "command": "supabase",
      "useCase": "Supabase projects",
      "description": "Manage local Supabase development and database workflows from the terminal.",
      "agentUse": "Use project commands and database tooling within an agent’s development workflow.",
      "features": [
        "Local development",
        "Database migrations",
        "Project management"
      ],
      "example": "supabase --help",
      "featured": false,
      "website": "https://github.com/supabase/cli#readme",
      "docs": "https://github.com/supabase/cli#readme",
      "stars": 2411,
      "license": null,
      "checkedAt": "2026-09-09T23:50:57.496Z"
    },
    {
      "slug": "docker-cli",
      "name": "Docker CLI",
      "repo": "docker/cli",
      "category": "Cloud & deployment",
      "command": "docker",
      "useCase": "Containers",
      "description": "Inspect and manage containers, images, and Docker environments.",
      "agentUse": "Let an agent query container state and use the documented Docker command interface.",
      "features": [
        "Container commands",
        "Image management",
        "Environment inspection"
      ],
      "example": "docker ps --format json",
      "featured": false,
      "website": "https://github.com/docker/cli#readme",
      "docs": "https://docs.docker.com/reference/cli/docker/",
      "stars": 6047,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:58.539Z"
    },
    {
      "slug": "kubectl",
      "name": "kubectl",
      "repo": "kubernetes/kubectl",
      "category": "Cloud & deployment",
      "command": "kubectl",
      "useCase": "Kubernetes clusters",
      "description": "Inspect and manage Kubernetes resources through the command line.",
      "agentUse": "Read cluster resources in structured formats and use Kubernetes command workflows.",
      "features": [
        "Resource inspection",
        "JSON and YAML output",
        "Kubernetes commands"
      ],
      "example": "kubectl get pods -o json",
      "featured": false,
      "website": "https://github.com/kubernetes/kubectl#readme",
      "docs": "https://github.com/kubernetes/kubectl#readme",
      "stars": 3336,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:58.425Z"
    },
    {
      "slug": "fd",
      "name": "fd",
      "repo": "sharkdp/fd",
      "category": "Code search",
      "command": "fd",
      "useCase": "Find files",
      "description": "Find files and directories with a concise command-line interface.",
      "agentUse": "Locate files by name, extension, or path before an agent reads their contents.",
      "features": [
        "File discovery",
        "Pattern matching",
        "Directory search"
      ],
      "example": "fd --help",
      "featured": false,
      "website": "https://github.com/sharkdp/fd#readme",
      "docs": "https://github.com/sharkdp/fd#readme",
      "stars": 44349,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:50:58.332Z"
    },
    {
      "slug": "ast-grep",
      "name": "ast-grep",
      "repo": "ast-grep/ast-grep",
      "category": "Code search",
      "command": "ast-grep",
      "useCase": "Structural code search",
      "description": "Search and rewrite code using syntax-aware patterns.",
      "agentUse": "Find code structures through an AST-based command-line interface.",
      "features": [
        "AST search",
        "Structural patterns",
        "Code rewriting"
      ],
      "example": "ast-grep --help",
      "featured": false,
      "website": "https://github.com/ast-grep/ast-grep#readme",
      "docs": "https://github.com/ast-grep/ast-grep#readme",
      "stars": 15829,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:50:58.431Z"
    },
    {
      "slug": "scc",
      "name": "scc",
      "repo": "boyter/scc",
      "category": "Code search",
      "command": "scc",
      "useCase": "Codebase statistics",
      "description": "Count lines of code and summarize language usage in a repository.",
      "agentUse": "Give an agent a quick inventory of a codebase before planning work.",
      "features": [
        "Language statistics",
        "Line counts",
        "Repository summaries"
      ],
      "example": "scc --help",
      "featured": false,
      "website": "https://github.com/boyter/scc#readme",
      "docs": "https://github.com/boyter/scc#readme",
      "stars": 8729,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:50:59.332Z"
    },
    {
      "slug": "yq",
      "name": "yq",
      "repo": "mikefarah/yq",
      "category": "Data & APIs",
      "command": "yq",
      "useCase": "Process YAML",
      "description": "Query and transform YAML and other structured data from the terminal.",
      "agentUse": "Read configuration values and transform structured files in shell workflows.",
      "features": [
        "YAML queries",
        "Data transformation",
        "Configuration processing"
      ],
      "example": "yq --help",
      "featured": false,
      "website": "https://github.com/mikefarah/yq#readme",
      "docs": "https://github.com/mikefarah/yq#readme",
      "stars": 15944,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:50:59.252Z"
    },
    {
      "slug": "httpie",
      "name": "HTTPie",
      "repo": "httpie/cli",
      "category": "Data & APIs",
      "command": "http",
      "useCase": "HTTP requests",
      "description": "Send HTTP requests and inspect responses from the terminal.",
      "agentUse": "Use a readable request CLI for API exploration and response inspection.",
      "features": [
        "HTTP requests",
        "API inspection",
        "JSON requests"
      ],
      "example": "http --help",
      "featured": false,
      "website": "https://github.com/httpie/cli#readme",
      "docs": "https://github.com/httpie/cli#readme",
      "stars": 38489,
      "license": "BSD-3-Clause",
      "checkedAt": "2026-09-09T23:50:59.367Z"
    },
    {
      "slug": "curl",
      "name": "curl",
      "repo": "curl/curl",
      "category": "Data & APIs",
      "command": "curl",
      "useCase": "Transfer data",
      "description": "Transfer data and inspect network responses through a command-line client.",
      "agentUse": "Call HTTP endpoints and handle responses in an agent’s shell workflow.",
      "features": [
        "HTTP requests",
        "Data transfer",
        "Response headers"
      ],
      "example": "curl --head https://example.com",
      "featured": false,
      "website": "https://github.com/curl/curl#readme",
      "docs": "https://github.com/curl/curl#readme",
      "stars": 42821,
      "license": null,
      "checkedAt": "2026-09-09T23:50:59.332Z"
    },
    {
      "slug": "uv",
      "name": "uv",
      "repo": "astral-sh/uv",
      "category": "Packages & environments",
      "command": "uv",
      "useCase": "Python environments",
      "description": "Manage Python packages, projects, tools, and environments with one CLI.",
      "agentUse": "Create reproducible Python environments and run project commands from the terminal.",
      "features": [
        "Python packages",
        "Virtual environments",
        "Tool execution"
      ],
      "example": "uv --help",
      "featured": false,
      "website": "https://github.com/astral-sh/uv#readme",
      "docs": "https://github.com/astral-sh/uv#readme",
      "stars": 89663,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:51:00.157Z"
    },
    {
      "slug": "pnpm",
      "name": "pnpm",
      "repo": "pnpm/pnpm",
      "category": "Packages & environments",
      "command": "pnpm",
      "useCase": "JavaScript packages",
      "description": "Manage JavaScript dependencies and workspace scripts.",
      "agentUse": "Run package and workspace operations as part of an agent’s development workflow.",
      "features": [
        "Dependency management",
        "Workspace support",
        "Package scripts"
      ],
      "example": "pnpm --help",
      "featured": false,
      "website": "https://github.com/pnpm/pnpm#readme",
      "docs": "https://github.com/pnpm/pnpm#readme",
      "stars": 36470,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:51:00.114Z"
    },
    {
      "slug": "bun",
      "name": "Bun",
      "repo": "oven-sh/bun",
      "category": "Packages & environments",
      "command": "bun",
      "useCase": "JavaScript tooling",
      "description": "Run JavaScript and TypeScript with a runtime and integrated command-line tools.",
      "agentUse": "Use the runtime, package manager, and test commands for JavaScript projects.",
      "features": [
        "JavaScript runtime",
        "Package management",
        "Test runner"
      ],
      "example": "bun --help",
      "featured": false,
      "website": "https://github.com/oven-sh/bun#readme",
      "docs": "https://github.com/oven-sh/bun#readme",
      "stars": 95923,
      "license": null,
      "checkedAt": "2026-09-09T23:51:00.221Z"
    },
    {
      "slug": "mise",
      "name": "mise",
      "repo": "jdx/mise",
      "category": "Packages & environments",
      "command": "mise",
      "useCase": "Development environments",
      "description": "Manage development tool versions, environment variables, and project tasks.",
      "agentUse": "Give an agent a consistent toolchain and documented project task commands.",
      "features": [
        "Tool versions",
        "Environment management",
        "Task execution"
      ],
      "example": "mise --help",
      "featured": false,
      "website": "https://github.com/jdx/mise#readme",
      "docs": "https://github.com/jdx/mise#readme",
      "stars": 33712,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:51:00.224Z"
    },
    {
      "slug": "ruff",
      "name": "Ruff",
      "repo": "astral-sh/ruff",
      "category": "Testing & quality",
      "command": "ruff",
      "useCase": "Python quality",
      "description": "Lint and format Python code from the command line.",
      "agentUse": "Return actionable Python diagnostics and apply documented formatting workflows.",
      "features": [
        "Python linting",
        "Code formatting",
        "Machine-readable diagnostics"
      ],
      "example": "ruff check --output-format json .",
      "featured": false,
      "website": "https://github.com/astral-sh/ruff#readme",
      "docs": "https://docs.astral.sh/ruff/",
      "stars": 49565,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:51:00.944Z"
    },
    {
      "slug": "biome",
      "name": "Biome",
      "repo": "biomejs/biome",
      "category": "Testing & quality",
      "command": "biome",
      "useCase": "JavaScript quality",
      "description": "Format and lint web-project code with an integrated toolchain.",
      "agentUse": "Check code quality through a CLI that fits automated development workflows.",
      "features": [
        "Code formatting",
        "Lint diagnostics",
        "Project checks"
      ],
      "example": "biome --help",
      "featured": false,
      "website": "https://github.com/biomejs/biome#readme",
      "docs": "https://github.com/biomejs/biome#readme",
      "stars": 25751,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:51:01.087Z"
    },
    {
      "slug": "semgrep",
      "name": "Semgrep",
      "repo": "semgrep/semgrep",
      "category": "Testing & quality",
      "command": "semgrep",
      "useCase": "Static analysis",
      "description": "Scan code for patterns and potential security issues with configurable rules.",
      "agentUse": "Run rule-based code checks and inspect findings through command-line workflows.",
      "features": [
        "Static analysis",
        "Code patterns",
        "Rule-based scanning"
      ],
      "example": "semgrep --help",
      "featured": false,
      "website": "https://github.com/semgrep/semgrep#readme",
      "docs": "https://github.com/semgrep/semgrep#readme",
      "stars": 16569,
      "license": "LGPL-2.1",
      "checkedAt": "2026-09-09T23:51:01.124Z"
    },
    {
      "slug": "gitleaks",
      "name": "Gitleaks",
      "repo": "gitleaks/gitleaks",
      "category": "Testing & quality",
      "command": "gitleaks",
      "useCase": "Secret detection",
      "description": "Scan source code and Git history for potential leaked credentials.",
      "agentUse": "Add a command-line secret scan to an agent’s code-review workflow.",
      "features": [
        "Secret scanning",
        "Git history scanning",
        "Scan reports"
      ],
      "example": "gitleaks --help",
      "featured": false,
      "website": "https://github.com/gitleaks/gitleaks#readme",
      "docs": "https://github.com/gitleaks/gitleaks#readme",
      "stars": 29190,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:51:01.047Z"
    },
    {
      "slug": "rclone",
      "name": "rclone",
      "repo": "rclone/rclone",
      "category": "Files & documents",
      "command": "rclone",
      "useCase": "Remote files",
      "description": "Manage files across local storage and supported remote storage providers.",
      "agentUse": "Use documented file commands to inspect storage and automate file workflows.",
      "features": [
        "Remote storage",
        "File listing",
        "File transfers"
      ],
      "example": "rclone --help",
      "featured": false,
      "website": "https://github.com/rclone/rclone#readme",
      "docs": "https://github.com/rclone/rclone#readme",
      "stars": 59664,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:51:01.939Z"
    },
    {
      "slug": "pandoc",
      "name": "Pandoc",
      "repo": "jgm/pandoc",
      "category": "Files & documents",
      "command": "pandoc",
      "useCase": "Convert documents",
      "description": "Convert documents between Markdown, HTML, and other supported formats.",
      "agentUse": "Transform source documents into formats needed by an agent’s publishing workflow.",
      "features": [
        "Document conversion",
        "Markdown processing",
        "Format support"
      ],
      "example": "pandoc --list-input-formats",
      "featured": false,
      "website": "https://github.com/jgm/pandoc#readme",
      "docs": "https://github.com/jgm/pandoc#readme",
      "stars": 46206,
      "license": "GPL-2.0",
      "checkedAt": "2026-09-09T23:51:01.871Z"
    },
    {
      "slug": "bat",
      "name": "bat",
      "repo": "sharkdp/bat",
      "category": "Files & documents",
      "command": "bat",
      "useCase": "Read source files",
      "description": "Read source files in the terminal with optional syntax highlighting.",
      "agentUse": "Use plain, unpaged output when passing file contents through an automated workflow.",
      "features": [
        "File viewing",
        "Syntax highlighting",
        "Plain output"
      ],
      "example": "bat --style=plain --paging=never README.md",
      "featured": false,
      "website": "https://github.com/sharkdp/bat#readme",
      "docs": "https://github.com/sharkdp/bat#readme",
      "stars": 60394,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-09T23:51:01.842Z"
    },
    {
      "slug": "glow",
      "name": "Glow",
      "repo": "charmbracelet/glow",
      "category": "Files & documents",
      "command": "glow",
      "useCase": "Read Markdown",
      "description": "Render Markdown documents in the terminal.",
      "agentUse": "Inspect project documentation using a terminal Markdown renderer.",
      "features": [
        "Markdown rendering",
        "Terminal output",
        "Local documents"
      ],
      "example": "glow --help",
      "featured": false,
      "website": "https://github.com/charmbracelet/glow#readme",
      "docs": "https://github.com/charmbracelet/glow#readme",
      "stars": 27239,
      "license": "MIT",
      "checkedAt": "2026-09-09T23:51:02.060Z"
    },
    {
      "slug": "firecrawl-cli",
      "name": "Firecrawl CLI",
      "repo": "firecrawl/cli",
      "category": "Browser automation",
      "command": "firecrawl",
      "useCase": "Web content extraction",
      "description": "Search, scrape, crawl, and extract web content.",
      "agentUse": "Use firecrawl to search, scrape, crawl, and extract web content.",
      "features": [
        "Web search",
        "Website crawling",
        "Content extraction"
      ],
      "example": "firecrawl scrape https://example.com",
      "featured": false,
      "website": "https://github.com/firecrawl/cli#readme",
      "docs": "https://github.com/firecrawl/cli#readme",
      "stars": 628,
      "license": null,
      "checkedAt": "2026-09-10T00:42:08.958965+00:00"
    },
    {
      "slug": "peekaboo",
      "name": "Peekaboo",
      "repo": "openclaw/Peekaboo",
      "category": "Productivity & communication",
      "command": "peekaboo",
      "useCase": "Native macOS automation",
      "description": "Inspect and control native macOS applications.",
      "agentUse": "Use peekaboo to inspect and control native macOS applications.",
      "features": [
        "Screenshots",
        "Accessibility inspection",
        "Application control"
      ],
      "example": "peekaboo see --app Finder --json",
      "featured": false,
      "website": "https://github.com/openclaw/Peekaboo#readme",
      "docs": "https://github.com/openclaw/Peekaboo#readme",
      "stars": 5140,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:07.970633+00:00"
    },
    {
      "slug": "qmd",
      "name": "QMD",
      "repo": "tobi/qmd",
      "category": "Files & documents",
      "command": "qmd",
      "useCase": "Search local knowledge",
      "description": "Search local documents with keyword and semantic search.",
      "agentUse": "Use qmd to search local documents with keyword and semantic search.",
      "features": [
        "Keyword search",
        "Semantic search",
        "Document collections"
      ],
      "example": "qmd search \"authentication\" --json -n 10",
      "featured": false,
      "website": "https://github.com/tobi/qmd#readme",
      "docs": "https://github.com/tobi/qmd#readme",
      "stars": 29636,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:07.950443+00:00"
    },
    {
      "slug": "mcporter",
      "name": "MCPorter",
      "repo": "openclaw/mcporter",
      "category": "Data & APIs",
      "command": "mcporter",
      "useCase": "MCP tool access",
      "description": "Call MCP tools from the terminal and generate CLIs.",
      "agentUse": "Use mcporter to call MCP tools from the terminal and generate CLIs.",
      "features": [
        "Server discovery",
        "MCP tool calls",
        "CLI generation"
      ],
      "example": "mcporter list",
      "featured": false,
      "website": "https://github.com/openclaw/mcporter#readme",
      "docs": "https://github.com/openclaw/mcporter#readme",
      "stars": 5001,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:07.991909+00:00"
    },
    {
      "slug": "repomix",
      "name": "Repomix",
      "repo": "yamadashy/repomix",
      "category": "Files & documents",
      "command": "repomix",
      "useCase": "Repository context packaging",
      "description": "Package repositories into files for LLM context.",
      "agentUse": "Use repomix to package repositories into files for LLM context.",
      "features": [
        "Repository packing",
        "LLM context",
        "File filtering"
      ],
      "example": "repomix --help",
      "featured": false,
      "website": "https://github.com/yamadashy/repomix#readme",
      "docs": "https://github.com/yamadashy/repomix#readme",
      "stars": 28270,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:09.435966+00:00"
    },
    {
      "slug": "summarize",
      "name": "Summarize",
      "repo": "steipete/summarize",
      "category": "Files & documents",
      "command": "summarize",
      "useCase": "Summarize source material",
      "description": "Extract and summarize webpages, videos, podcasts, and files.",
      "agentUse": "Use summarize to extract and summarize webpages, videos, podcasts, and files.",
      "features": [
        "Webpage extraction",
        "Media transcripts",
        "File summaries"
      ],
      "example": "summarize \"https://example.com\" --extract --plain",
      "featured": false,
      "website": "https://github.com/steipete/summarize#readme",
      "docs": "https://github.com/steipete/summarize#readme",
      "stars": 6607,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:09.391872+00:00"
    },
    {
      "slug": "shot-scraper",
      "name": "shot-scraper",
      "repo": "simonw/shot-scraper",
      "category": "Browser automation",
      "command": "shot-scraper",
      "useCase": "Website capture and scraping",
      "description": "Capture website screenshots and scrape using JavaScript.",
      "agentUse": "Use shot-scraper to capture website screenshots and scrape using JavaScript.",
      "features": [
        "Screenshots",
        "JavaScript scraping",
        "Browser automation"
      ],
      "example": "shot-scraper https://example.com/",
      "featured": false,
      "website": "https://github.com/simonw/shot-scraper#readme",
      "docs": "https://github.com/simonw/shot-scraper#readme",
      "stars": 2566,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:09.603974+00:00"
    },
    {
      "slug": "google-workspace-cli",
      "name": "Google Workspace CLI (gws)",
      "repo": "googleworkspace/cli",
      "category": "Productivity & communication",
      "command": "gws",
      "useCase": "Google Workspace automation",
      "description": "Operate Gmail, Drive, Calendar, Docs, and Sheets.",
      "agentUse": "Use gws to operate Gmail, Drive, Calendar, Docs, and Sheets.",
      "features": [
        "Gmail and Calendar",
        "Drive and Docs",
        "Sheets API"
      ],
      "example": "gws drive files list --params '{\"pageSize\": 5}'",
      "featured": false,
      "website": "https://github.com/googleworkspace/cli#readme",
      "docs": "https://github.com/googleworkspace/cli#readme",
      "stars": 30814,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:10.646417+00:00"
    },
    {
      "slug": "gogcli",
      "name": "gogcli (gog)",
      "repo": "openclaw/gogcli",
      "category": "Productivity & communication",
      "command": "gog",
      "useCase": "Google account workflows",
      "description": "Manage Google services with structured output and account routing.",
      "agentUse": "Use gog to manage Google services with structured output and account routing.",
      "features": [
        "Account routing",
        "Structured output",
        "Google services"
      ],
      "example": "gog --readonly gmail search 'is:unread newer_than:7d' --max 10 --json",
      "featured": false,
      "website": "https://github.com/openclaw/gogcli#readme",
      "docs": "https://github.com/openclaw/gogcli#readme",
      "stars": 8392,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:11.033904+00:00"
    },
    {
      "slug": "linear-cli",
      "name": "Linear CLI",
      "repo": "schpet/linear-cli",
      "category": "Git & collaboration",
      "command": "linear",
      "useCase": "Linear issue workflows",
      "description": "Manage Linear issues and associated development workflows.",
      "agentUse": "Use linear to manage Linear issues and associated development workflows.",
      "features": [
        "Issue search",
        "Status updates",
        "Branch workflows"
      ],
      "example": "linear issue query --search \"login bug\"",
      "featured": false,
      "website": "https://github.com/schpet/linear-cli#readme",
      "docs": "https://github.com/schpet/linear-cli#readme",
      "stars": 954,
      "license": "ISC",
      "checkedAt": "2026-09-10T00:42:11.014284+00:00"
    },
    {
      "slug": "beads",
      "name": "Beads (bd)",
      "repo": "gastownhall/beads",
      "category": "Git & collaboration",
      "command": "bd",
      "useCase": "Task dependency tracking",
      "description": "Track tasks, dependencies, blockers, and project memory.",
      "agentUse": "Use bd to track tasks, dependencies, blockers, and project memory.",
      "features": [
        "Task tracking",
        "Dependency graphs",
        "Project memory"
      ],
      "example": "bd ready --json",
      "featured": false,
      "website": "https://github.com/gastownhall/beads#readme",
      "docs": "https://github.com/gastownhall/beads#readme",
      "stars": 27008,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:11.237836+00:00"
    },
    {
      "slug": "himalaya",
      "name": "Himalaya",
      "repo": "pimalaya/himalaya",
      "category": "Productivity & communication",
      "command": "himalaya",
      "useCase": "Email workflows",
      "description": "Read, search, organize, and send email.",
      "agentUse": "Use himalaya to read, search, organize, and send email.",
      "features": [
        "Mailbox search",
        "Message organization",
        "Email sending"
      ],
      "example": "himalaya envelope list --page 2",
      "featured": false,
      "website": "https://github.com/pimalaya/himalaya#readme",
      "docs": "https://github.com/pimalaya/himalaya#readme",
      "stars": 7215,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:12.251847+00:00"
    },
    {
      "slug": "remindctl",
      "name": "remindctl",
      "repo": "openclaw/remindctl",
      "category": "Productivity & communication",
      "command": "remindctl",
      "useCase": "Apple Reminders workflows",
      "description": "Create, search, update, and complete Apple Reminders.",
      "agentUse": "Use remindctl to create, search, update, and complete Apple Reminders.",
      "features": [
        "Reminder search",
        "Due dates",
        "Task completion"
      ],
      "example": "remindctl search \"project\" --completed --json",
      "featured": false,
      "website": "https://github.com/openclaw/remindctl#readme",
      "docs": "https://github.com/openclaw/remindctl#readme",
      "stars": 361,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:12.715989+00:00"
    },
    {
      "slug": "imsg",
      "name": "imsg",
      "repo": "openclaw/imsg",
      "category": "Productivity & communication",
      "command": "imsg",
      "useCase": "Apple Messages access",
      "description": "Read and send messages through Apple Messages.",
      "agentUse": "Use imsg to read and send messages through Apple Messages.",
      "features": [
        "Chat history",
        "Message watching",
        "Message sending"
      ],
      "example": "imsg chats --limit 10 --json",
      "featured": false,
      "website": "https://github.com/openclaw/imsg#readme",
      "docs": "https://github.com/openclaw/imsg#readme",
      "stars": 1316,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:12.747879+00:00"
    },
    {
      "slug": "wacli",
      "name": "wacli",
      "repo": "openclaw/wacli",
      "category": "Productivity & communication",
      "command": "wacli",
      "useCase": "WhatsApp workflows",
      "description": "Synchronize, search, and send WhatsApp messages.",
      "agentUse": "Use wacli to synchronize, search, and send WhatsApp messages.",
      "features": [
        "Message synchronization",
        "Message search",
        "Message sending"
      ],
      "example": "wacli --read-only --json messages search \"invoice\"",
      "featured": false,
      "website": "https://github.com/openclaw/wacli#readme",
      "docs": "https://github.com/openclaw/wacli#readme",
      "stars": 2727,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:13.071037+00:00"
    },
    {
      "slug": "sonoscli",
      "name": "sonoscli",
      "repo": "steipete/sonoscli",
      "category": "Productivity & communication",
      "command": "sonos",
      "useCase": "Sonos playback control",
      "description": "Control Sonos speakers and playback.",
      "agentUse": "Use sonos to control Sonos speakers and playback.",
      "features": [
        "Speaker discovery",
        "Playback control",
        "Speaker grouping"
      ],
      "example": "sonos --help",
      "featured": false,
      "website": "https://github.com/steipete/sonoscli#readme",
      "docs": "https://github.com/steipete/sonoscli#readme",
      "stars": 185,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:13.746973+00:00"
    },
    {
      "slug": "goplaces",
      "name": "goplaces",
      "repo": "openclaw/goplaces",
      "category": "Data & APIs",
      "command": "goplaces",
      "useCase": "Google Places lookup",
      "description": "Search places and retrieve Google Places information.",
      "agentUse": "Use goplaces to search places and retrieve Google Places information.",
      "features": [
        "Place search",
        "Place details",
        "JSON output"
      ],
      "example": "goplaces search \"coffee near Central Park\" --limit 5 --json",
      "featured": false,
      "website": "https://github.com/openclaw/goplaces#readme",
      "docs": "https://github.com/openclaw/goplaces#readme",
      "stars": 252,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:14.331605+00:00"
    },
    {
      "slug": "railway-cli",
      "name": "Railway CLI",
      "repo": "railwayapp/cli",
      "category": "Cloud & deployment",
      "command": "railway",
      "useCase": "Railway service operations",
      "description": "Operate Railway projects and services.",
      "agentUse": "Use railway to operate Railway projects and services.",
      "features": [
        "Project management",
        "Service deployment",
        "Deployment logs"
      ],
      "example": "railway --help",
      "featured": false,
      "website": "https://github.com/railwayapp/cli#readme",
      "docs": "https://github.com/railwayapp/cli#readme",
      "stars": 604,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:14.282123+00:00"
    },
    {
      "slug": "aws-cli",
      "name": "AWS CLI",
      "repo": "aws/aws-cli",
      "category": "Cloud & deployment",
      "command": "aws",
      "useCase": "AWS resource management",
      "description": "Manage AWS compute, storage, networking, and other services.",
      "agentUse": "Use aws to manage AWS compute, storage, networking, and other services.",
      "features": [
        "Compute resources",
        "Object storage",
        "Service APIs"
      ],
      "example": "aws --version",
      "featured": false,
      "website": "https://github.com/aws/aws-cli#readme",
      "docs": "https://github.com/aws/aws-cli#readme",
      "stars": 17243,
      "license": null,
      "checkedAt": "2026-09-10T00:42:14.641499+00:00"
    },
    {
      "slug": "azure-cli",
      "name": "Azure CLI",
      "repo": "Azure/azure-cli",
      "category": "Cloud & deployment",
      "command": "az",
      "useCase": "Azure resource management",
      "description": "Create and manage Azure resources.",
      "agentUse": "Use az to create and manage Azure resources.",
      "features": [
        "Resource groups",
        "Cloud services",
        "Account management"
      ],
      "example": "az --help",
      "featured": false,
      "website": "https://github.com/Azure/azure-cli#readme",
      "docs": "https://github.com/Azure/azure-cli#readme",
      "stars": 4622,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:15.366254+00:00"
    },
    {
      "slug": "doctl",
      "name": "DigitalOcean (doctl)",
      "repo": "digitalocean/doctl",
      "category": "Cloud & deployment",
      "command": "doctl",
      "useCase": "DigitalOcean operations",
      "description": "Manage droplets, databases, Kubernetes, and other resources.",
      "agentUse": "Use doctl to manage droplets, databases, Kubernetes, and other resources.",
      "features": [
        "Droplets",
        "Managed databases",
        "Kubernetes clusters"
      ],
      "example": "doctl --help",
      "featured": false,
      "website": "https://github.com/digitalocean/doctl#readme",
      "docs": "https://github.com/digitalocean/doctl#readme",
      "stars": 3449,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:16.154857+00:00"
    },
    {
      "slug": "hcloud",
      "name": "Hetzner Cloud (hcloud)",
      "repo": "hetznercloud/cli",
      "category": "Cloud & deployment",
      "command": "hcloud",
      "useCase": "Hetzner Cloud operations",
      "description": "Manage cloud servers, networks, volumes, and load balancers.",
      "agentUse": "Use hcloud to manage cloud servers, networks, volumes, and load balancers.",
      "features": [
        "Cloud servers",
        "Networks and volumes",
        "Load balancers"
      ],
      "example": "hcloud --help",
      "featured": false,
      "website": "https://github.com/hetznercloud/cli#readme",
      "docs": "https://github.com/hetznercloud/cli#readme",
      "stars": 1801,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:16.090010+00:00"
    },
    {
      "slug": "scaleway-cli",
      "name": "Scaleway CLI",
      "repo": "scaleway/scaleway-cli",
      "category": "Cloud & deployment",
      "command": "scw",
      "useCase": "Scaleway resource management",
      "description": "Manage Scaleway cloud resources.",
      "agentUse": "Use scw to manage Scaleway cloud resources.",
      "features": [
        "Compute instances",
        "Cloud resources",
        "Resource listing"
      ],
      "example": "scw instance server list",
      "featured": false,
      "website": "https://github.com/scaleway/scaleway-cli#readme",
      "docs": "https://github.com/scaleway/scaleway-cli#readme",
      "stars": 997,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:16.279995+00:00"
    },
    {
      "slug": "linode-cli",
      "name": "Linode CLI",
      "repo": "linode/linode-cli",
      "category": "Cloud & deployment",
      "command": "linode-cli",
      "useCase": "Linode infrastructure operations",
      "description": "Operate Linode infrastructure through its API.",
      "agentUse": "Use linode-cli to operate Linode infrastructure through its API.",
      "features": [
        "Compute instances",
        "API access",
        "Resource management"
      ],
      "example": "linode-cli --help",
      "featured": false,
      "website": "https://github.com/linode/linode-cli#readme",
      "docs": "https://github.com/linode/linode-cli#readme",
      "stars": 440,
      "license": "BSD-3-Clause",
      "checkedAt": "2026-09-10T00:42:17.055259+00:00"
    },
    {
      "slug": "ovhcloud-cli",
      "name": "OVHcloud CLI",
      "repo": "ovh/ovhcloud-cli",
      "category": "Cloud & deployment",
      "command": "ovhcloud",
      "useCase": "OVHcloud service operations",
      "description": "Manage OVHcloud services.",
      "agentUse": "Use ovhcloud to manage OVHcloud services.",
      "features": [
        "Cloud services",
        "Resource management",
        "Service APIs"
      ],
      "example": "ovhcloud --help",
      "featured": false,
      "website": "https://github.com/ovh/ovhcloud-cli#readme",
      "docs": "https://github.com/ovh/ovhcloud-cli#readme",
      "stars": 175,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:17.608884+00:00"
    },
    {
      "slug": "netlify-cli",
      "name": "Netlify CLI",
      "repo": "netlify/cli",
      "category": "Cloud & deployment",
      "command": "netlify",
      "useCase": "Netlify development and deployment",
      "description": "Develop locally and deploy Netlify sites.",
      "agentUse": "Use netlify to develop locally and deploy Netlify sites.",
      "features": [
        "Local development",
        "Site deployments",
        "Project management"
      ],
      "example": "netlify --help",
      "featured": false,
      "website": "https://github.com/netlify/cli#readme",
      "docs": "https://github.com/netlify/cli#readme",
      "stars": 1915,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:17.786430+00:00"
    },
    {
      "slug": "render-cli",
      "name": "Render CLI",
      "repo": "render-oss/cli",
      "category": "Cloud & deployment",
      "command": "render",
      "useCase": "Render service operations",
      "description": "Manage Render services and deployments.",
      "agentUse": "Use render to manage Render services and deployments.",
      "features": [
        "Service management",
        "Deployments",
        "Logs"
      ],
      "example": "render --help",
      "featured": false,
      "website": "https://github.com/render-oss/cli#readme",
      "docs": "https://render.com/docs/cli",
      "stars": 114,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:17.872100+00:00"
    },
    {
      "slug": "firebase-cli",
      "name": "Firebase CLI",
      "repo": "firebase/firebase-tools",
      "category": "Cloud & deployment",
      "command": "firebase",
      "useCase": "Firebase project workflows",
      "description": "Deploy Firebase projects and run local emulators.",
      "agentUse": "Use firebase to deploy Firebase projects and run local emulators.",
      "features": [
        "Project deployment",
        "Local emulators",
        "Firebase services"
      ],
      "example": "firebase --help",
      "featured": false,
      "website": "https://github.com/firebase/firebase-tools#readme",
      "docs": "https://github.com/firebase/firebase-tools#readme",
      "stars": 4465,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:18.616324+00:00"
    },
    {
      "slug": "neonctl",
      "name": "Neon CLI (neonctl)",
      "repo": "neondatabase/neonctl",
      "category": "Data & APIs",
      "command": "neonctl",
      "useCase": "Postgres database branching",
      "description": "Manage Postgres projects and database branches.",
      "agentUse": "Use neonctl to manage Postgres projects and database branches.",
      "features": [
        "Project management",
        "Database branches",
        "Connection strings"
      ],
      "example": "neonctl projects list",
      "featured": false,
      "website": "https://github.com/neondatabase/neonctl#readme",
      "docs": "https://github.com/neondatabase/neonctl#readme",
      "stars": 117,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:19.610252+00:00"
    },
    {
      "slug": "ecctl",
      "name": "Elastic Cloud (ecctl)",
      "repo": "elastic/ecctl",
      "category": "Cloud & deployment",
      "command": "ecctl",
      "useCase": "Elastic Cloud operations",
      "description": "Operate Elastic Cloud deployments through its APIs.",
      "agentUse": "Use ecctl to operate Elastic Cloud deployments through its APIs.",
      "features": [
        "Deployment management",
        "Cloud API access",
        "Resource inspection"
      ],
      "example": "ecctl --help",
      "featured": false,
      "website": "https://github.com/elastic/ecctl#readme",
      "docs": "https://github.com/elastic/ecctl#readme",
      "stars": 58,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:19.664843+00:00"
    },
    {
      "slug": "stripe-cli",
      "name": "Stripe CLI",
      "repo": "stripe/stripe-cli",
      "category": "Data & APIs",
      "command": "stripe",
      "useCase": "Stripe API development",
      "description": "Manage API objects, test webhooks, inspect request logs.",
      "agentUse": "Use stripe to manage API objects, test webhooks, inspect request logs.",
      "features": [
        "API objects",
        "Webhook testing",
        "Request logs"
      ],
      "example": "stripe --help",
      "featured": false,
      "website": "https://github.com/stripe/stripe-cli#readme",
      "docs": "https://github.com/stripe/stripe-cli#readme",
      "stars": 2173,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:19.924406+00:00"
    },
    {
      "slug": "wp-cli",
      "name": "WP-CLI",
      "repo": "wp-cli/wp-cli",
      "category": "Data & APIs",
      "command": "wp",
      "useCase": "WordPress administration",
      "description": "Manage WordPress content, plugins, users, and configuration.",
      "agentUse": "Use wp to manage WordPress content, plugins, users, and configuration.",
      "features": [
        "Content management",
        "Plugin management",
        "User administration"
      ],
      "example": "wp help",
      "featured": false,
      "website": "https://github.com/wp-cli/wp-cli#readme",
      "docs": "https://github.com/wp-cli/wp-cli#readme",
      "stars": 5147,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:20.406150+00:00"
    },
    {
      "slug": "shopify-cli",
      "name": "Shopify CLI",
      "repo": "Shopify/cli",
      "category": "Cloud & deployment",
      "command": "shopify",
      "useCase": "Shopify development",
      "description": "Build and deploy Shopify apps, themes, and storefronts.",
      "agentUse": "Use shopify to build and deploy Shopify apps, themes, and storefronts.",
      "features": [
        "App development",
        "Theme workflows",
        "Storefront deployment"
      ],
      "example": "shopify --help",
      "featured": false,
      "website": "https://github.com/Shopify/cli#readme",
      "docs": "https://github.com/Shopify/cli#readme",
      "stars": 742,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:21.367159+00:00"
    },
    {
      "slug": "salesforce-cli",
      "name": "Salesforce CLI (sf)",
      "repo": "salesforcecli/cli",
      "category": "Cloud & deployment",
      "command": "sf",
      "useCase": "Salesforce development",
      "description": "Develop, test, and deploy Salesforce projects.",
      "agentUse": "Use sf to develop, test, and deploy Salesforce projects.",
      "features": [
        "Project development",
        "Test execution",
        "Deployment workflows"
      ],
      "example": "sf --help",
      "featured": false,
      "website": "https://github.com/salesforcecli/cli#readme",
      "docs": "https://github.com/salesforcecli/cli#readme",
      "stars": 180,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:21.696620+00:00"
    },
    {
      "slug": "microsoft-365-cli",
      "name": "CLI for Microsoft 365",
      "repo": "pnp/cli-microsoft365",
      "category": "Productivity & communication",
      "command": "m365",
      "useCase": "Microsoft 365 administration",
      "description": "Manage Microsoft 365 and SharePoint resources.",
      "agentUse": "Use m365 to manage Microsoft 365 and SharePoint resources.",
      "features": [
        "SharePoint sites",
        "Microsoft 365 resources",
        "Structured output"
      ],
      "example": "m365 spo site get --help",
      "featured": false,
      "website": "https://github.com/pnp/cli-microsoft365#readme",
      "docs": "https://github.com/pnp/cli-microsoft365#readme",
      "stars": 1443,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:21.570088+00:00"
    },
    {
      "slug": "twilio-cli",
      "name": "Twilio CLI",
      "repo": "twilio/twilio-cli",
      "category": "Data & APIs",
      "command": "twilio",
      "useCase": "Twilio API workflows",
      "description": "Operate Twilio APIs and communications resources.",
      "agentUse": "Use twilio to operate Twilio APIs and communications resources.",
      "features": [
        "API access",
        "Communications resources",
        "Account workflows"
      ],
      "example": "twilio --help",
      "featured": false,
      "website": "https://github.com/twilio/twilio-cli#readme",
      "docs": "https://github.com/twilio/twilio-cli#readme",
      "stars": 192,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:22.278640+00:00"
    },
    {
      "slug": "algolia-cli",
      "name": "Algolia CLI",
      "repo": "algolia/cli",
      "category": "Data & APIs",
      "command": "algolia",
      "useCase": "Search index management",
      "description": "Manage search indices, records, and configuration.",
      "agentUse": "Use algolia to manage search indices, records, and configuration.",
      "features": [
        "Search indices",
        "Record management",
        "Index configuration"
      ],
      "example": "algolia --help",
      "featured": false,
      "website": "https://github.com/algolia/cli#readme",
      "docs": "https://github.com/algolia/cli#readme",
      "stars": 109,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:22.961523+00:00"
    },
    {
      "slug": "contentful-cli",
      "name": "Contentful CLI",
      "repo": "contentful/contentful-cli",
      "category": "Data & APIs",
      "command": "contentful",
      "useCase": "Contentful content operations",
      "description": "Manage spaces and import, export, or migrate content.",
      "agentUse": "Use contentful to manage spaces and import, export, or migrate content.",
      "features": [
        "Space management",
        "Content import and export",
        "Content migration"
      ],
      "example": "contentful space --help",
      "featured": false,
      "website": "https://github.com/contentful/contentful-cli#readme",
      "docs": "https://github.com/contentful/contentful-cli#readme",
      "stars": 361,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:24.254004+00:00"
    },
    {
      "slug": "sanity-cli",
      "name": "Sanity CLI",
      "repo": "sanity-io/cli",
      "category": "Data & APIs",
      "command": "sanity",
      "useCase": "Sanity project management",
      "description": "Manage datasets, validate schemas, and deploy projects.",
      "agentUse": "Use sanity to manage datasets, validate schemas, and deploy projects.",
      "features": [
        "Dataset management",
        "Schema validation",
        "Project deployment"
      ],
      "example": "sanity --help",
      "featured": false,
      "website": "https://github.com/sanity-io/cli#readme",
      "docs": "https://github.com/sanity-io/cli#readme",
      "stars": 8,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:23.660763+00:00"
    },
    {
      "slug": "podman",
      "name": "Podman",
      "repo": "podman-container-tools/podman",
      "category": "Cloud & deployment",
      "command": "podman",
      "useCase": "Container and pod management",
      "description": "Build and manage containers and pods.",
      "agentUse": "Use podman to build and manage containers and pods.",
      "features": [
        "Container images",
        "Container execution",
        "Pod management"
      ],
      "example": "podman --help",
      "featured": false,
      "website": "https://github.com/podman-container-tools/podman#readme",
      "docs": "https://github.com/podman-container-tools/podman#readme",
      "stars": 32826,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:23.952897+00:00"
    },
    {
      "slug": "helm",
      "name": "Helm",
      "repo": "helm/helm",
      "category": "Cloud & deployment",
      "command": "helm",
      "useCase": "Kubernetes package management",
      "description": "Install, upgrade, and manage Kubernetes applications.",
      "agentUse": "Use helm to install, upgrade, and manage Kubernetes applications.",
      "features": [
        "Chart installation",
        "Release upgrades",
        "Application management"
      ],
      "example": "helm --help",
      "featured": false,
      "website": "https://github.com/helm/helm#readme",
      "docs": "https://github.com/helm/helm#readme",
      "stars": 30228,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:24.467620+00:00"
    },
    {
      "slug": "opentofu",
      "name": "OpenTofu",
      "repo": "opentofu/opentofu",
      "category": "Cloud & deployment",
      "command": "tofu",
      "useCase": "Infrastructure provisioning",
      "description": "Plan and provision infrastructure from configuration.",
      "agentUse": "Use tofu to plan and provision infrastructure from configuration.",
      "features": [
        "Infrastructure plans",
        "Resource provisioning",
        "Configuration workflows"
      ],
      "example": "tofu --help",
      "featured": false,
      "website": "https://github.com/opentofu/opentofu#readme",
      "docs": "https://github.com/opentofu/opentofu#readme",
      "stars": 30141,
      "license": "MPL-2.0",
      "checkedAt": "2026-09-10T00:42:25.369784+00:00"
    },
    {
      "slug": "pulumi",
      "name": "Pulumi",
      "repo": "pulumi/pulumi",
      "category": "Cloud & deployment",
      "command": "pulumi",
      "useCase": "Infrastructure as code",
      "description": "Provision infrastructure using programming languages.",
      "agentUse": "Use pulumi to provision infrastructure using programming languages.",
      "features": [
        "Programming language support",
        "Infrastructure previews",
        "Resource provisioning"
      ],
      "example": "pulumi --help",
      "featured": false,
      "website": "https://github.com/pulumi/pulumi#readme",
      "docs": "https://github.com/pulumi/pulumi#readme",
      "stars": 25658,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:25.426089+00:00"
    },
    {
      "slug": "ansible",
      "name": "Ansible",
      "repo": "ansible/ansible",
      "category": "Cloud & deployment",
      "command": "ansible",
      "useCase": "Server configuration automation",
      "description": "Configure servers and execute deployment playbooks.",
      "agentUse": "Use ansible to configure servers and execute deployment playbooks.",
      "features": [
        "Server configuration",
        "Inventory management",
        "Deployment playbooks"
      ],
      "example": "ansible --help",
      "featured": false,
      "website": "https://github.com/ansible/ansible#readme",
      "docs": "https://github.com/ansible/ansible#readme",
      "stars": 70620,
      "license": "GPL-3.0",
      "checkedAt": "2026-09-10T00:42:26.031476+00:00"
    },
    {
      "slug": "argocd",
      "name": "Argo CD CLI",
      "repo": "argoproj/argo-cd",
      "category": "Cloud & deployment",
      "command": "argocd",
      "useCase": "Kubernetes deployment synchronization",
      "description": "Synchronize and manage Kubernetes application deployments.",
      "agentUse": "Use argocd to synchronize and manage Kubernetes application deployments.",
      "features": [
        "Application synchronization",
        "Deployment status",
        "GitOps workflows"
      ],
      "example": "argocd --help",
      "featured": false,
      "website": "https://github.com/argoproj/argo-cd#readme",
      "docs": "https://github.com/argoproj/argo-cd#readme",
      "stars": 24114,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:26.040262+00:00"
    },
    {
      "slug": "flux-cli",
      "name": "Flux CLI",
      "repo": "fluxcd/flux2",
      "category": "Cloud & deployment",
      "command": "flux",
      "useCase": "GitOps delivery management",
      "description": "Bootstrap and manage GitOps delivery workflows.",
      "agentUse": "Use flux to bootstrap and manage GitOps delivery workflows.",
      "features": [
        "Cluster bootstrap",
        "Delivery reconciliation",
        "GitOps resources"
      ],
      "example": "flux --help",
      "featured": false,
      "website": "https://github.com/fluxcd/flux2#readme",
      "docs": "https://github.com/fluxcd/flux2#readme",
      "stars": 8390,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:27.140472+00:00"
    },
    {
      "slug": "kind",
      "name": "kind",
      "repo": "kubernetes-sigs/kind",
      "category": "Cloud & deployment",
      "command": "kind",
      "useCase": "Disposable Kubernetes clusters",
      "description": "Create disposable Kubernetes clusters for testing.",
      "agentUse": "Use kind to create disposable Kubernetes clusters for testing.",
      "features": [
        "Local clusters",
        "Container-based nodes",
        "Test environments"
      ],
      "example": "kind --help",
      "featured": false,
      "website": "https://github.com/kubernetes-sigs/kind#readme",
      "docs": "https://github.com/kubernetes-sigs/kind#readme",
      "stars": 15481,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:27.256098+00:00"
    },
    {
      "slug": "minikube",
      "name": "minikube",
      "repo": "kubernetes/minikube",
      "category": "Cloud & deployment",
      "command": "minikube",
      "useCase": "Local Kubernetes environments",
      "description": "Run and manage local Kubernetes environments.",
      "agentUse": "Use minikube to run and manage local Kubernetes environments.",
      "features": [
        "Local clusters",
        "Cluster management",
        "Development environments"
      ],
      "example": "minikube --help",
      "featured": false,
      "website": "https://github.com/kubernetes/minikube#readme",
      "docs": "https://github.com/kubernetes/minikube#readme",
      "stars": 32113,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:27.570592+00:00"
    },
    {
      "slug": "sops",
      "name": "SOPS",
      "repo": "getsops/sops",
      "category": "Security & secrets",
      "command": "sops",
      "useCase": "Encrypted configuration",
      "description": "Encrypt and decrypt configuration and secret files.",
      "agentUse": "Use sops to encrypt and decrypt configuration and secret files.",
      "features": [
        "Configuration encryption",
        "Secret file editing",
        "Decryption"
      ],
      "example": "sops --help",
      "featured": false,
      "website": "https://github.com/getsops/sops#readme",
      "docs": "https://github.com/getsops/sops#readme",
      "stars": 23071,
      "license": "MPL-2.0",
      "checkedAt": "2026-09-10T00:42:27.600955+00:00"
    },
    {
      "slug": "age",
      "name": "age",
      "repo": "FiloSottile/age",
      "category": "Security & secrets",
      "command": "age",
      "useCase": "File encryption",
      "description": "Encrypt and decrypt files in shell workflows.",
      "agentUse": "Use age to encrypt and decrypt files in shell workflows.",
      "features": [
        "File encryption",
        "File decryption",
        "Shell workflows"
      ],
      "example": "age --help",
      "featured": false,
      "website": "https://github.com/FiloSottile/age#readme",
      "docs": "https://github.com/FiloSottile/age#readme",
      "stars": 23504,
      "license": "BSD-3-Clause",
      "checkedAt": "2026-09-10T00:42:28.563973+00:00"
    },
    {
      "slug": "bitwarden-cli",
      "name": "Bitwarden CLI",
      "repo": "bitwarden/clients",
      "category": "Security & secrets",
      "command": "bw",
      "useCase": "Password vault automation",
      "description": "Access and manage vault items programmatically.",
      "agentUse": "Use bw to access and manage vault items programmatically.",
      "features": [
        "Vault item access",
        "Vault synchronization",
        "Item management"
      ],
      "example": "bw --help",
      "featured": false,
      "website": "https://github.com/bitwarden/clients#readme",
      "docs": "https://bitwarden.com/help/cli/",
      "stars": 13761,
      "license": null,
      "checkedAt": "2026-09-10T00:42:28.947699+00:00"
    },
    {
      "slug": "doppler-cli",
      "name": "Doppler CLI",
      "repo": "DopplerHQ/cli",
      "category": "Security & secrets",
      "command": "doppler",
      "useCase": "Application secret delivery",
      "description": "Retrieve and inject secrets into applications.",
      "agentUse": "Use doppler to retrieve and inject secrets into applications.",
      "features": [
        "Secret retrieval",
        "Environment injection",
        "Project configuration"
      ],
      "example": "doppler --help",
      "featured": false,
      "website": "https://github.com/DopplerHQ/cli#readme",
      "docs": "https://github.com/DopplerHQ/cli#readme",
      "stars": 392,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:29.505805+00:00"
    },
    {
      "slug": "infisical-cli",
      "name": "Infisical CLI",
      "repo": "Infisical/cli",
      "category": "Security & secrets",
      "command": "infisical",
      "useCase": "Application secrets management",
      "description": "Inject, export, and manage application secrets.",
      "agentUse": "Use infisical to inject, export, and manage application secrets.",
      "features": [
        "Secret injection",
        "Secret export",
        "Environment management"
      ],
      "example": "infisical --help",
      "featured": false,
      "website": "https://github.com/Infisical/cli#readme",
      "docs": "https://github.com/Infisical/cli#readme",
      "stars": 91,
      "license": null,
      "checkedAt": "2026-09-10T00:42:29.441459+00:00"
    },
    {
      "slug": "trivy",
      "name": "Trivy",
      "repo": "aquasecurity/trivy",
      "category": "Testing & quality",
      "command": "trivy",
      "useCase": "Container and repository security",
      "description": "Scan containers and repositories for security issues.",
      "agentUse": "Use trivy to scan containers and repositories for security issues.",
      "features": [
        "Vulnerability scanning",
        "Misconfiguration checks",
        "Repository scanning"
      ],
      "example": "trivy --help",
      "featured": false,
      "website": "https://github.com/aquasecurity/trivy#readme",
      "docs": "https://github.com/aquasecurity/trivy#readme",
      "stars": 37848,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:30.376387+00:00"
    },
    {
      "slug": "syft",
      "name": "Syft",
      "repo": "anchore/syft",
      "category": "Testing & quality",
      "command": "syft",
      "useCase": "Software inventory generation",
      "description": "Generate software bills of materials.",
      "agentUse": "Use syft to generate software bills of materials.",
      "features": [
        "SBOM generation",
        "Image analysis",
        "Filesystem analysis"
      ],
      "example": "syft --help",
      "featured": false,
      "website": "https://github.com/anchore/syft#readme",
      "docs": "https://github.com/anchore/syft#readme",
      "stars": 9544,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:30.487344+00:00"
    },
    {
      "slug": "grype",
      "name": "Grype",
      "repo": "anchore/grype",
      "category": "Testing & quality",
      "command": "grype",
      "useCase": "Vulnerability detection",
      "description": "Find vulnerabilities in images and filesystems.",
      "agentUse": "Use grype to find vulnerabilities in images and filesystems.",
      "features": [
        "Image scanning",
        "Filesystem scanning",
        "Vulnerability reports"
      ],
      "example": "grype --help",
      "featured": false,
      "website": "https://github.com/anchore/grype#readme",
      "docs": "https://github.com/anchore/grype#readme",
      "stars": 12865,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:31.064544+00:00"
    },
    {
      "slug": "trufflehog",
      "name": "TruffleHog",
      "repo": "trufflesecurity/trufflehog",
      "category": "Testing & quality",
      "command": "trufflehog",
      "useCase": "Exposed credential detection",
      "description": "Find and verify exposed credentials.",
      "agentUse": "Use trufflehog to find and verify exposed credentials.",
      "features": [
        "Credential discovery",
        "Secret verification",
        "Repository scanning"
      ],
      "example": "trufflehog --help",
      "featured": false,
      "website": "https://github.com/trufflesecurity/trufflehog#readme",
      "docs": "https://github.com/trufflesecurity/trufflehog#readme",
      "stars": 27737,
      "license": "AGPL-3.0",
      "checkedAt": "2026-09-10T00:42:31.140083+00:00"
    },
    {
      "slug": "cosign",
      "name": "Cosign",
      "repo": "sigstore/cosign",
      "category": "Security & secrets",
      "command": "cosign",
      "useCase": "Artifact signature verification",
      "description": "Sign and verify container images and artifacts.",
      "agentUse": "Use cosign to sign and verify container images and artifacts.",
      "features": [
        "Image signing",
        "Artifact signatures",
        "Signature verification"
      ],
      "example": "cosign --help",
      "featured": false,
      "website": "https://github.com/sigstore/cosign#readme",
      "docs": "https://github.com/sigstore/cosign#readme",
      "stars": 6290,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:31.928802+00:00"
    },
    {
      "slug": "snyk-cli",
      "name": "Snyk CLI",
      "repo": "snyk/cli",
      "category": "Testing & quality",
      "command": "snyk",
      "useCase": "Project security scanning",
      "description": "Scan projects for security vulnerabilities.",
      "agentUse": "Use snyk to scan projects for security vulnerabilities.",
      "features": [
        "Dependency scanning",
        "Container scanning",
        "Security reports"
      ],
      "example": "snyk --help",
      "featured": false,
      "website": "https://github.com/snyk/cli#readme",
      "docs": "https://github.com/snyk/cli#readme",
      "stars": 5657,
      "license": null,
      "checkedAt": "2026-09-10T00:42:32.107479+00:00"
    },
    {
      "slug": "sentry-cli",
      "name": "Sentry CLI",
      "repo": "getsentry/cli",
      "category": "Testing & quality",
      "command": "sentry",
      "useCase": "Sentry issue investigation",
      "description": "Interact with Sentry from the terminal.",
      "agentUse": "Use sentry to interact with Sentry from the terminal.",
      "features": [
        "Issue inspection",
        "Event details",
        "Project access"
      ],
      "example": "sentry --help",
      "featured": false,
      "website": "https://github.com/getsentry/cli#readme",
      "docs": "https://github.com/getsentry/cli/tree/main/packages/cli#readme",
      "stars": 119,
      "license": null,
      "checkedAt": "2026-09-10T00:42:32.701793+00:00"
    },
    {
      "slug": "k6",
      "name": "k6",
      "repo": "grafana/k6",
      "category": "Testing & quality",
      "command": "k6",
      "useCase": "Load and performance testing",
      "description": "Execute load tests and measure performance.",
      "agentUse": "Use k6 to execute load tests and measure performance.",
      "features": [
        "Load test execution",
        "Performance metrics",
        "Scripted scenarios"
      ],
      "example": "k6 --help",
      "featured": false,
      "website": "https://github.com/grafana/k6#readme",
      "docs": "https://github.com/grafana/k6#readme",
      "stars": 31424,
      "license": "AGPL-3.0",
      "checkedAt": "2026-09-10T00:42:32.846527+00:00"
    },
    {
      "slug": "lighthouse",
      "name": "Lighthouse",
      "repo": "GoogleChrome/lighthouse",
      "category": "Testing & quality",
      "command": "lighthouse",
      "useCase": "Website quality audits",
      "description": "Audit website performance, accessibility, and best practices.",
      "agentUse": "Use lighthouse to audit website performance, accessibility, and best practices.",
      "features": [
        "Performance audits",
        "Accessibility audits",
        "Best-practice checks"
      ],
      "example": "lighthouse https://example.com",
      "featured": false,
      "website": "https://github.com/GoogleChrome/lighthouse#readme",
      "docs": "https://github.com/GoogleChrome/lighthouse#readme",
      "stars": 30749,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:33.513748+00:00"
    },
    {
      "slug": "axe-cli",
      "name": "axe CLI",
      "repo": "dequelabs/axe-core-npm",
      "category": "Testing & quality",
      "command": "axe",
      "useCase": "Web accessibility checks",
      "description": "Run automated web accessibility checks.",
      "agentUse": "Use axe to run automated web accessibility checks.",
      "features": [
        "Accessibility rules",
        "Page testing",
        "Violation reports"
      ],
      "example": "axe https://example.com",
      "featured": false,
      "website": "https://github.com/dequelabs/axe-core-npm#readme",
      "docs": "https://github.com/dequelabs/axe-core-npm/tree/develop/packages/cli#readme",
      "stars": 722,
      "license": "MPL-2.0",
      "checkedAt": "2026-09-10T00:42:33.664726+00:00"
    },
    {
      "slug": "duckdb-cli",
      "name": "DuckDB CLI",
      "repo": "duckdb/duckdb",
      "category": "Data & APIs",
      "command": "duckdb",
      "useCase": "Analytical SQL queries",
      "description": "Query CSV, Parquet, and other data using SQL.",
      "agentUse": "Use duckdb to query CSV, Parquet, and other data using SQL.",
      "features": [
        "CSV queries",
        "Parquet queries",
        "Embedded SQL"
      ],
      "example": "duckdb -c \"SELECT 42;\"",
      "featured": false,
      "website": "https://github.com/duckdb/duckdb#readme",
      "docs": "https://github.com/duckdb/duckdb#readme",
      "stars": 41107,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:34.255335+00:00"
    },
    {
      "slug": "sqlite-utils",
      "name": "sqlite-utils",
      "repo": "simonw/sqlite-utils",
      "category": "Data & APIs",
      "command": "sqlite-utils",
      "useCase": "SQLite data workflows",
      "description": "Create, query, and transform SQLite databases.",
      "agentUse": "Use sqlite-utils to create, query, and transform SQLite databases.",
      "features": [
        "Database creation",
        "SQL queries",
        "Data transformation"
      ],
      "example": "sqlite-utils --help",
      "featured": false,
      "website": "https://github.com/simonw/sqlite-utils#readme",
      "docs": "https://github.com/simonw/sqlite-utils#readme",
      "stars": 2167,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:34.219021+00:00"
    },
    {
      "slug": "dbt-core",
      "name": "dbt Core",
      "repo": "dbt-labs/dbt-core",
      "category": "Data & APIs",
      "command": "dbt",
      "useCase": "SQL data transformations",
      "description": "Build and test SQL data transformations.",
      "agentUse": "Use dbt to build and test SQL data transformations.",
      "features": [
        "SQL models",
        "Transformation builds",
        "Data tests"
      ],
      "example": "dbt --help",
      "featured": false,
      "website": "https://github.com/dbt-labs/dbt-core#readme",
      "docs": "https://github.com/dbt-labs/dbt-core#readme",
      "stars": 13795,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:35.022131+00:00"
    },
    {
      "slug": "sqlfluff",
      "name": "SQLFluff",
      "repo": "sqlfluff/sqlfluff",
      "category": "Testing & quality",
      "command": "sqlfluff",
      "useCase": "SQL linting and formatting",
      "description": "Lint and format SQL across dialects.",
      "agentUse": "Use sqlfluff to lint and format SQL across dialects.",
      "features": [
        "SQL linting",
        "SQL formatting",
        "Multiple dialects"
      ],
      "example": "sqlfluff --help",
      "featured": false,
      "website": "https://github.com/sqlfluff/sqlfluff#readme",
      "docs": "https://github.com/sqlfluff/sqlfluff#readme",
      "stars": 9866,
      "license": "MIT",
      "checkedAt": "2026-09-10T00:42:35.228861+00:00"
    },
    {
      "slug": "golang-migrate",
      "name": "golang-migrate",
      "repo": "golang-migrate/migrate",
      "category": "Data & APIs",
      "command": "migrate",
      "useCase": "Database migration execution",
      "description": "Apply and roll back database migrations.",
      "agentUse": "Use migrate to apply and roll back database migrations.",
      "features": [
        "Migration application",
        "Migration rollback",
        "Database drivers"
      ],
      "example": "migrate -help",
      "featured": false,
      "website": "https://github.com/golang-migrate/migrate#readme",
      "docs": "https://github.com/golang-migrate/migrate#readme",
      "stars": 18904,
      "license": null,
      "checkedAt": "2026-09-10T00:42:35.776106+00:00"
    },
    {
      "slug": "atlas",
      "name": "Atlas",
      "repo": "ariga/atlas",
      "category": "Data & APIs",
      "command": "atlas",
      "useCase": "Schema inspection and migration",
      "description": "Inspect schemas and plan database migrations.",
      "agentUse": "Use atlas to inspect schemas and plan database migrations.",
      "features": [
        "Schema inspection",
        "Schema diffs",
        "Migration planning"
      ],
      "example": "atlas --help",
      "featured": false,
      "website": "https://github.com/ariga/atlas#readme",
      "docs": "https://github.com/ariga/atlas#readme",
      "stars": 8715,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:35.892062+00:00"
    },
    {
      "slug": "miller",
      "name": "Miller (mlr)",
      "repo": "johnkerl/miller",
      "category": "Data & APIs",
      "command": "mlr",
      "useCase": "Tabular data processing",
      "description": "Filter, join, aggregate, and transform tabular data.",
      "agentUse": "Use mlr to filter, join, aggregate, and transform tabular data.",
      "features": [
        "Record filtering",
        "Joins and aggregation",
        "Data transformation"
      ],
      "example": "mlr --help",
      "featured": false,
      "website": "https://github.com/johnkerl/miller#readme",
      "docs": "https://github.com/johnkerl/miller#readme",
      "stars": 10015,
      "license": null,
      "checkedAt": "2026-09-10T00:42:36.589605+00:00"
    },
    {
      "slug": "dolt",
      "name": "Dolt",
      "repo": "dolthub/dolt",
      "category": "Data & APIs",
      "command": "dolt",
      "useCase": "Versioned database workflows",
      "description": "Branch, diff, merge, and query versioned databases.",
      "agentUse": "Use dolt to branch, diff, merge, and query versioned databases.",
      "features": [
        "SQL queries",
        "Database branching",
        "Database diffs and merges"
      ],
      "example": "dolt --help",
      "featured": false,
      "website": "https://github.com/dolthub/dolt#readme",
      "docs": "https://github.com/dolthub/dolt#readme",
      "stars": 24405,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:36.759996+00:00"
    },
    {
      "slug": "yt-dlp",
      "name": "yt-dlp",
      "repo": "yt-dlp/yt-dlp",
      "category": "Files & documents",
      "command": "yt-dlp",
      "useCase": "Video metadata and media retrieval",
      "description": "Retrieve video metadata, subtitles, and media.",
      "agentUse": "Use yt-dlp to retrieve video metadata, subtitles, and media.",
      "features": [
        "Video metadata",
        "Subtitle retrieval",
        "Media downloads"
      ],
      "example": "yt-dlp --help",
      "featured": false,
      "website": "https://github.com/yt-dlp/yt-dlp#readme",
      "docs": "https://github.com/yt-dlp/yt-dlp#readme",
      "stars": 190000,
      "license": "Unlicense",
      "checkedAt": "2026-09-10T00:42:37.266092+00:00"
    },
    {
      "slug": "ffmpeg",
      "name": "FFmpeg",
      "repo": "FFmpeg/FFmpeg",
      "category": "Files & documents",
      "command": "ffmpeg",
      "useCase": "Audio and video processing",
      "description": "Convert, trim, combine, and process audio and video.",
      "agentUse": "Use ffmpeg to convert, trim, combine, and process audio and video.",
      "features": [
        "Media conversion",
        "Trimming and combining",
        "Audio processing"
      ],
      "example": "ffmpeg -h",
      "featured": false,
      "website": "https://github.com/FFmpeg/FFmpeg#readme",
      "docs": "https://github.com/FFmpeg/FFmpeg#readme",
      "stars": 64081,
      "license": null,
      "checkedAt": "2026-09-10T00:42:37.378198+00:00"
    },
    {
      "slug": "imagemagick",
      "name": "ImageMagick",
      "repo": "ImageMagick/ImageMagick",
      "category": "Files & documents",
      "command": "magick",
      "useCase": "Image processing",
      "description": "Resize, convert, composite, and process images.",
      "agentUse": "Use magick to resize, convert, composite, and process images.",
      "features": [
        "Image resizing",
        "Format conversion",
        "Image composition"
      ],
      "example": "magick -help",
      "featured": false,
      "website": "https://github.com/ImageMagick/ImageMagick#readme",
      "docs": "https://github.com/ImageMagick/ImageMagick#readme",
      "stars": 17380,
      "license": null,
      "checkedAt": "2026-09-10T00:42:38.069815+00:00"
    },
    {
      "slug": "tesseract",
      "name": "Tesseract",
      "repo": "tesseract-ocr/tesseract",
      "category": "Files & documents",
      "command": "tesseract",
      "useCase": "Image text extraction",
      "description": "Extract text from images using OCR.",
      "agentUse": "Use tesseract to extract text from images using OCR.",
      "features": [
        "Optical character recognition",
        "Image input",
        "Text output"
      ],
      "example": "tesseract --help",
      "featured": false,
      "website": "https://github.com/tesseract-ocr/tesseract#readme",
      "docs": "https://github.com/tesseract-ocr/tesseract#readme",
      "stars": 76415,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:38.317395+00:00"
    },
    {
      "slug": "ocrmypdf",
      "name": "OCRmyPDF",
      "repo": "ocrmypdf/OCRmyPDF",
      "category": "Files & documents",
      "command": "ocrmypdf",
      "useCase": "Searchable scanned PDFs",
      "description": "Add searchable text to scanned PDFs.",
      "agentUse": "Use ocrmypdf to add searchable text to scanned PDFs.",
      "features": [
        "PDF OCR",
        "Searchable text layers",
        "Scanned documents"
      ],
      "example": "ocrmypdf --help",
      "featured": false,
      "website": "https://github.com/ocrmypdf/OCRmyPDF#readme",
      "docs": "https://github.com/ocrmypdf/OCRmyPDF#readme",
      "stars": 34705,
      "license": "MPL-2.0",
      "checkedAt": "2026-09-10T00:42:38.651019+00:00"
    },
    {
      "slug": "qpdf",
      "name": "qpdf",
      "repo": "qpdf/qpdf",
      "category": "Files & documents",
      "command": "qpdf",
      "useCase": "PDF inspection and transformation",
      "description": "Inspect, split, merge, and transform PDF files.",
      "agentUse": "Use qpdf to inspect, split, merge, and transform PDF files.",
      "features": [
        "PDF inspection",
        "Splitting and merging",
        "PDF transformations"
      ],
      "example": "qpdf --help",
      "featured": false,
      "website": "https://github.com/qpdf/qpdf#readme",
      "docs": "https://github.com/qpdf/qpdf#readme",
      "stars": 5398,
      "license": "Apache-2.0",
      "checkedAt": "2026-09-10T00:42:39.014402+00:00"
    },
    {
      "slug": "restic",
      "name": "restic",
      "repo": "restic/restic",
      "category": "Files & documents",
      "command": "restic",
      "useCase": "Encrypted backup workflows",
      "description": "Create, verify, and restore encrypted backups.",
      "agentUse": "Use restic to create, verify, and restore encrypted backups.",
      "features": [
        "Encrypted backups",
        "Backup verification",
        "File restoration"
      ],
      "example": "restic --help",
      "featured": false,
      "website": "https://github.com/restic/restic#readme",
      "docs": "https://github.com/restic/restic#readme",
      "stars": 35953,
      "license": "BSD-2-Clause",
      "checkedAt": "2026-09-10T00:42:39.523244+00:00"
    },
    {
      "slug": "just",
      "name": "just",
      "repo": "casey/just",
      "category": "Packages & environments",
      "command": "just",
      "useCase": "Project command execution",
      "description": "Execute predefined project commands and workflows.",
      "agentUse": "Use just to execute predefined project commands and workflows.",
      "features": [
        "Task recipes",
        "Project commands",
        "Shell workflows"
      ],
      "example": "just --list",
      "featured": false,
      "website": "https://github.com/casey/just#readme",
      "docs": "https://github.com/casey/just#readme",
      "stars": 35708,
      "license": "CC0-1.0",
      "checkedAt": "2026-09-10T00:42:39.767421+00:00"
    }
  ],
  "categories": [
    "Git & collaboration",
    "Browser automation",
    "Code search",
    "Data & APIs",
    "Agents & models",
    "Cloud & deployment",
    "Packages & environments",
    "Testing & quality",
    "Files & documents",
    "Productivity & communication",
    "Security & secrets"
  ]
};
